### ISSUE TITLE
ReaEQ plugin crashes but only for a few of its GUI elements

### ISSUE THREAD

**Issue by ariutti** [Spacechild1/vstplugin#10]
Hi guys, I am taking my first steps with the **VSTPlugin** Quark in SuperCollider. 

I am working on 

- Windows 10 Pro
- Supercollider 3.11.2
- VSTPlugin version 0.5.4

I wanted to use a simple graphical equalizer at the end of my sound pipeline, so I decided to load a plugin I am used to: the [ReaEQ](https://www.reaper.fm/reaplugs/) from Cockos.

Here is the code I am using, which is basically copied and pasted from the documentation.

```
s.boot;

(
SynthDef(\insert, { arg bus;
    Out.ar(bus, VSTPlugin.ar(In.ar(bus, 2), 2));
	//ReplaceOut.ar(bus, VSTPlugin.ar(In.ar(bus, 2), 2));
}).add;
)


// create the synth:
~synth = Synth(\insert, [\bus, 0]);

// get a handle to the VSTPlugin:
~fx = VSTPluginController(~synth);

// open a plugin by name/key (might require VSTPlugin.search!)
~fx.open("C:/Program Files/VSTPlugins/ReaPlugs/reaeq-standalone.dll", editor: true, verbose: true);


~fx.numParameters; // il plugin reaEQ ha 12 parametri

// show the generic plugin GUI:
~fx.gui;

// show the VST editor:
~fx.editor(show:true);
```

I first notice that on the SuperCollider side the plugin seems to have only 12 controllable parameters (evaluating these lines):

```
~fx.numParameters; 
~fx.gui; 
```

![03_VST_gui](https://user-images.githubusercontent.com/6818509/196202236-2b3270f0-e3e2-4a47-b504-f102f17d9ed7.JPG)

while opening the same plugin as a VST in insert within DAW Reaper, it also shows some other controllable parameters such as:

- Enable (checkbox);
- Type (drop-down menu);
- Log-scale automated frequencies (checkbox);
- gain (slider);
- add band / remove band, etc...

![01_VST_da_Reaper](https://user-images.githubusercontent.com/6818509/196202298-d2c078e9-c74d-4185-a059-fab9542a8828.JPG)

I notice that by opening the "proprietary" plugin interface through the VSTPluginController (method .editor(show:true) ), it is cropped and does not show all the GUI elements.

![02_VST_da_SC](https://user-images.githubusercontent.com/6818509/196202373-21f792e2-d045-4d40-be07-1fda85cc42e8.JPG)

In addition, the plugin crashes whenever I attempt to change any of the settings, it would seem, that are not among the 12 "really" visible by SuperCollider.

How to fix this?
Thank you so much for your great work and for your help and support

**Comment by ariutti** [comment]
Thank you @Spacechild1 for your reply,
I crash it everytime I use the:

- _Enable_ checkbox;
- _Type_ drop-down menu;
- _Log-scale automated frequencies_ checkbox;

**Comment by Spacechild1** [comment]
Ok, I see the problem. The plugins send a weird parameter change message whenever you automate one of these parameters. The Pd version can handle it, but the SC version apparently doesn't. Should be an easy fix.

The wrong window dimension is annoying. I hope I can fix it!

**Comment by Spacechild1** [comment]
The crash should now be fixed on the develop branch. Please give it a try!

Regarding the window size bug: this might take a while to fix, but as a workaround you can add a `return true;` statement at the beginning of the `bool Window::canResize` method in `WindowWin32.cpp`, so that the window will at least be resizable.

**Comment by ariutti** [comment]
Thank you so much @Spacechild1 for your instructions.
I was able to compile it from the _develop_ branch (also using your workaround for the resize).

Now it works as expected: 

- I can click on the previously borken GUI elements and the plugin doesn't crash.
- I'm also able to reveal the missing part of the GUI resizing the window.

Don't know if this can be useful or not but now if I add a new band and moving some of its parameters, I see some warning messages on the post windows complaining I'm using out of range parameters.

![04_VST_gui_now_not_crash_and_resizable](https://user-images.githubusercontent.com/6818509/196402062-94b85764-2dc5-4fd3-9d6a-827fed2fdd34.JPG)

I believe this is normal behavior since, at an initial calculation, when the plugin was first loaded, there were only 12 editable parameters. The new band controls doesn't appear in the default editor when I evaluate the `.gui` method on the VSTPluginController instance.

(BTW: this project is super cool - congratulations and thank you very much for your work)

**Comment by Spacechild1** [comment]
> I believe this is normal behavior since, at an initial calculation, when the plugin was first loaded, there were only 12 editable parameters. The new band controls doesn't appear in the default editor when I evaluate the .gui method on the VSTPluginController instance.

Yes, that's exactly what's happening. I've now pushed another fix to develop that completely ignores out-of-range parameter automation messages.

> Is this because such a slider has some different behavior than the other controls?

For whatever reason, the "Gain" slider is not part of the exposed VST parameters.

To be honest, the ReaPlugs implementation is a bit wonky. There is no reason why these parameters should be hidden from the generic interface in the first place.

**Comment by Spacechild1** [comment]
Looks like the wrong window size of ReaPlugs has already been reported (https://git.iem.at/pd/vstplugin/-/issues/171), so I think I can close this issue.

Thanks again for reporting!
