### ISSUE TITLE
SimpleDecoder.vst3 "configuration" not accessible

### ISSUE THREAD

**Issue by escuta** [Spacechild1/vstplugin#11]
Dear devs, In SuperCollider, when the IEM "SimpleDecoder.vst3" plugin (from the IEM Plugin Suite) is opened via VSTPluginController, there is no option to load the speaker configuration file (a *.json file). At least not via the .gui method for the controller instance, only a list of "built in programs" and user presets. Sorry if I've missed something.

**Comment by Spacechild1** [comment]
Hi, you can open the "native" plugin UI with the `.editor` method and load the config file from there. Then you can save the plugin state as a preset with `.writeProgram` and recall it later with `.readProgram`.

**Comment by escuta** [comment]
Fantastic. Thanks for your help.
