### ISSUE TITLE
Reason Rack Plugin not receive midi incoming (pd)

### ISSUE THREAD

**Issue by DSBhproject** [Spacechild1/vstplugin#13]
Hi, congratulation for [vstplugin~] which is pretty useful. I've notice that after update from 0.3... reason rack plugin vst3 doesn't work, with older version it worked nice and I've only noticed in this plugin. Audio pass through and even param_set works but midi_note and midi_noteoff doesn't work anymore. I'm sure this is not a reason issue since I don't update it so this should be related with certain changes on external. Btw I'm on pd 0.52. Thanks

**Comment by Spacechild1** [comment]
Hi, that's really strange. People (including me) use all sorts of VST instruments with MIDI messages and there has never been a problem with note-on and note-off messages. Unfortunately, there is no demo version for Reason Rack plugin, so I am not sure how to proceed...

Just to be clear: you're saying that it still works on 0.3, but fails on newer versions? Please find out which version is the first one that breaks.

BTW, what's your OS?

**Comment by DSBhproject** [comment]
Ok I'll try to find the first version where it doesn't work. I'm on win 10. Well reason rack plugin come with reason daw, not separately, so maybe it comes with the ful DAW demo.

**Comment by Spacechild1** [comment]
You can find all versions on Deken. However, Deken hides old versions by default. You have to untick "Only show the newest version" in the Deken settings:

![grafik](https://user-images.githubusercontent.com/16126632/213566944-f5fa8460-cb5b-4dda-a7e6-e38cc3d7fa04.png)

**Comment by Spacechild1** [comment]
Thanks! That's strange. I compared v0.5 and v0.5.1 and there are no changes in the MIDI handling code...

Can you also try the latest development version? https://git.iem.at/pd/vstplugin/-/jobs/44810/artifacts/download?file_type=archive

Make sure that in the Pd console it says "vstplugin~ 0.6-pre1".

Also, can you share a minimal test patch that triggers the problem?

**Comment by DSBhproject** [comment]
-Also, can you share a minimal test patch that triggers the problem?
It'd necessarily involve to have reason rack plugin.
Anyways it works now on v0.6-pre1 : )

**Comment by Spacechild1** [comment]
> Anyways it works now on v0.6-pre1 : )

Wow, that's great news :-) I will keep this issue open until the 0.6 release. Thanks for reporting!
