### ISSUE TITLE
Search plugins "permission denied" in Ubuntu 22.04

### ISSUE THREAD

**Issue by JRSV** [Spacechild1/vstplugin#16]
Hello

I am running into a problem and cannot figure put how to fix it. When I search directories, I get a "permission denied". I have tried copying plugins to other directories that I am certain to have permission.

I am running Ubuntu 22.04, pd 0.54.1 and latest deken release of vstplugin~ 

any ideas how can I fix this?

**Comment by Spacechild1** [comment]
What are the permission of the `host` executable? Also, please post the output of the Pd console.

**Comment by JRSV** [comment]
Ok, sorry for the delay, I decided to do a fresh install of AVLinux, hoping to solve. Unfortunately it is not an OS problem. Previous versions of vstplugin~ worked with no issue.

to your questions, 

permissions for host executable are read write, I did encounter the contrary though so I made sure the plugins were "owned" by me. The Pd window keeps saying the contrary, I get "permission Denied [13]"

`probing '/home/jrsv/.vst/AllGVSTLinux64Beta/GBand.so'... error! couldn't run subprocess host: Permission denied [13]
vstplugin~: can't open '/home/jrsv/.vst/AllGVSTLinux64Beta/GBand.so'
print: open 0`

I will try to test the previous version of [vstplugin~] to see if the problem is in the update.

any ideas?

cheers

**Comment by Spacechild1** [comment]
> permissions for host executable are read write

It must also be executable! 

> couldn't run subprocess host: Permission denied [13]

Yeah, looks like `host` is not executable for some reason... Do `chmod 755 host` and try again.

**Comment by JRSV** [comment]
ok, so I am really puzzled, I do not understand what is going on, I even tried the most extreme which was to make RWX for everyone..

`ls -l`
`-rwxrwxrwx 1 jrsv audio 6544088 Feb 12  2023 libAllRADecoder.so
-rwxrwxrwx 1 jrsv audio 6327752 Feb 12  2023 libBinauralDecoder.so
-rwxrwxrwx 1 jrsv audio 5507800 Feb 12  2023 libCoordinateConverter.so
-rwxrwxrwx 1 jrsv audio 5532376 Feb 12  2023 libDirectionalCompressor.so
-rwxrwxrwx 1 jrsv audio 5966552 Feb 12  2023 libDirectivityShaper.so
-rwxrwxrwx 1 jrsv audio 5495512 Feb 12  2023 libDistanceCompensator.so
-rwxrwxrwx 1 jrsv audio 5511896 Feb 12  2023 libDualDelay.so
-rwxrwxrwx 1 jrsv audio 5925592 Feb 12  2023 libEnergyVisualizer.so
-rwxrwxrwx 1 jrsv audio 5913304 Feb 12  2023 libFdnReverb.so
-rwxrwxrwx 1 jrsv audio 5552856 Feb 12  2023 libGranularEncoder.so
-rwxrwxrwx 1 jrsv audio 5421784 Feb 12  2023 libMatrixMultiplier.so
-rwxrwxrwx 1 jrsv audio 5978840 Feb 12  2023 libMultiBandCompressor.so
-rwxrwxrwx 1 jrsv audio 5556952 Feb 12  2023 libMultiEncoder.so
-rwxrwxrwx 1 jrsv audio 5888728 Feb 12  2023 libMultiEQ.so
-rwxrwxrwx 1 jrsv audio 5487320 Feb 12  2023 libOmniCompressor.so
-rwxrwxrwx 1 jrsv audio 5479128 Feb 12  2023 libProbeDecoder.so
-rwxrwxrwx 1 jrsv audio 6413016 Feb 12  2023 libRoomEncoder.so
-rwxrwxrwx 1 jrsv audio 5634776 Feb 12  2023 libSceneRotator.so
-rwxrwxrwx 1 jrsv audio 6134744 Feb 12  2023 libSimpleDecoder.so
-rwxrwxrwx 1 jrsv audio 5503704 Feb 12  2023 libStereoEncoder.so
-rwxrwxrwx 1 jrsv audio 5429976 Feb 12  2023 libToolBox.so`

however I still cannot load the plugins and Pd window gives me the same error

`probing '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'... error! couldn't run subprocess host: Permission denied [13]
vstplugin~: can't open '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'
print: open 0
probing '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'... error! couldn't run subprocess host: Permission denied [13]
vstplugin~: can't open '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'
print: open 0
probing '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'... error! couldn't run subprocess host: Permission denied [13]
vstplugin~: can't open '/usr/lib/x86_64-linux-gnu/iem-plugin-suite/vst/libAllRADecoder.so'
print: open 0`

any ideas??

**Comment by Spacechild1** [comment]
There was a misunderstanding. I have been talking about the permissions of the `host` executable (next to `vstplugin~.pd_linux`), not about the plugins!

Please check the permissions of the `host` executable.

**Comment by JRSV** [comment]
Ok!!! now I got something. Ran into a little problem though, I have a plugin called VASTvaporizer2.vst3, which is not loading as the Pd window is stuck in `waiting for '/usr/lib/vst3/VASTvaporizer2.vst3` it does not black list it or anything and continues even if I close the patch. Is there a way to exclude this plugin? or do I have to move it?

**Comment by Spacechild1** [comment]
> Is there a way to exclude this plugin? or do I have to move it?

Yes! Check the `-x` flag for the `[search(` message. Alternatively, you can also set a probe timeout with the `-t` flag.

The remaining question is how you ended up with a non-executable `host` binary. When I download `vstplugin~-v0.6-pre1` here on Debian, `host` has the correct permissions (`rwxr-xr-x`). In fact, I know a few Linux users who have been testing the release and nobody had problems with permissions.

**Comment by JRSV** [comment]
I know!!! I decided to check what happened, I suspect this happened when I reinstalled my OS to theDebian machine I mentioned, as I checked the version and it was V. 0.5.1. I have now downloaded it again from Deken and v-0.6 is up and correctly running. Either way it was good to understand permissions and ownerships for the host executables. Sorry for the noise... and thanks for this object

**Comment by Spacechild1** [comment]
You're welcome!
