### ISSUE TITLE
Error: static assertion failed due to requirement. IntType must be a supported integer type

### ISSUE THREAD

**Issue by retroriff** [Spacechild1/vstplugin#18]
Hello,

I encountered an issue while building the VST extension for SuperCollider after updating my Apple M1 to macOS Sequoia. I also updated SuperCollider to version 3.13 and attempted to rebuild the VST extension using the following cmake command:

```
cmake -DSC=ON -DPD=OFF -DSC_INCLUDEDIR=/Users/<MY_USER>/Downloads/supercollider-develop -DVST2=OFF -DBUILD_HOST_AMD64=ON -DCMAKE_OSX_ARCHITECTURES=x86_64 ..
```
However I am getting this error:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr/include/c++/v1/__random/uniform_int_distribution.h:138:17: error: static assertion failed due to requirement '__libcpp_random_is_valid_inttype<char>::value': IntType must be a supported integer type
  138 |   static_assert(__libcpp_random_is_valid_inttype<_IntType>::value, "IntType must be a supported integer type");
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The result is:
```
[ 77%] Built target vst_amd64
make: *** [all] Error 2
```

It might be related to an incompatibility between the Xcode SDK and the architecture settings. Any help or suggestions would be appreciated.

Thank you

**Comment by retroriff** [comment]
I will close it because I finally decide to skip it and use the binaries.

**Comment by Spacechild1** [comment]
AFAICT, `std::random` is only used by the test suite, so you can work around the issue by setting the `TESTSUITE` CMake variable to `OFF`.

However, I'd still like to know what's going on. Can you post the *full* compiler output, ideally as a text file?

**Comment by retroriff** [comment]
Hi, after disabling the TESTSUITE I was able to install it, un-quarantined and then I executed VSTPlugin.search.

Now the extension can be executed but I get this message:

```
(
Ndef(\vst, \vst -> {
    var sig = WhiteNoise.ar(0.1) ! 2;
    sig = VSTPlugin.ar(sig, 2, id: \fx1);
    sig = VSTPlugin.ar(sig, 2, id: \fx2);
}).play;
​
~fx = VSTPluginNodeProxyController.collect(Ndef(\vst));
~fx.fx1.open("ValhallaFreqEcho", editor: true);
)

WARNING: 'ValhallaFreqEcho' is neither an existing plugin name nor a valid file path.
````

When I run `VSTPlugin.print`, it says:
```
ValhallaFreqEcho.vst3 (Valhalla DSP, LLC) [/Library/Audio/Plug-Ins/VST3/ValhallaFreqEcho.vst3]
```
This plugin used to work before my update. Am I missing something?

Here's the output of my previous issue, with TESTSUITE ON:

[output.txt](https://github.com/user-attachments/files/18053508/output.txt)

**Comment by Spacechild1** [comment]
> `~fx.fx1.open("ValhallaFreqEcho", editor: true);`

You just forgot the `.vst3` suffix. `VSTPlugin.print` actually showed the correct key, but it's easy to overlook.

> Here's the output of my previous issue, with TESTSUITE ON:

Thanks! Turns out this is a bug I've already fixed 6 months ago on the develop branch, but I completely forgot about it :) https://git.iem.at/pd/vstplugin/-/commit/1a0dd9440e1469eed9c214bf88eec180059384af

I think we can close this issue now for good. If you encounter more problems, feel free to open new issues! If possible, please use the official issue tracker: https://git.iem.at/pd/vstplugin/-/issues
