### ISSUE TITLE
ERROR: couldn't load 'C:/Program Files/Common Files/VST2/ZynAddSubFX.dll': Wrong CPU architecture

### ISSUE THREAD

**Issue by Catsvilles** [Spacechild1/vstplugin#3]
Sorry to bother again, but I could not solve nor find the origin of this issue on my own. So, I have download ZynAddSubFX as a VST plugin from here: https://www.kvraudio.com/forum/viewtopic.php?t=268277
Using in on Windows 7 as a standalone or as VST plugin in a regular DAW seems to be fine, but when trying to load it in SC I get the error above after which it is blacklisted and cannot be opened.
Can this be an issue with VSTplugin since ZynAddSubFX.dll works fine in other hosts? Really hope for some help, thank you!

**Comment by Spacechild1** [comment]
Hi, the error message actual tells you the problem: `Wrong CPU architecture`. As far as I can see, ZynAddSubFX is only provided as a 32-bit binary. I guess, you're using the 64-bit version of Supercollider, so it can't load the plugin. The next version of VSTPlugin will support bit-bridging (loading 32-bit plugins in a 64-bit host and vice versa), like many DAWs, but in the meantime you have to either
a) compile a 64-bit version of ZynAddSubFX (or nag the author to do so) or 
b) use 32-bit Supercollider.
