### ISSUE TITLE
[feature request] vstplugin~ for ARM (raspberry pi)

### ISSUE THREAD

**Issue by oliverstotz** [Spacechild1/vstplugin#9]
Hi, it would be great to have [vstplugin~] compiled for ARM architecture.

You wrote in your last mail on the list:
"[vstplugin~] has a built-in plugin bridge and winelib is also available for ARM, so you would not even need a third-party plugin wrapper. "

Would that mean that i don't need a full WINE or WINEHQ install on the RPI to make the bridging work, just the winelib ? If so, could you provide a little HOWTO in order to use standalone .dlls on a raspberry pi without the whole WINE overhead ? Or am i getting the wrong idea ?

Anyway: [vstplugin*] on a RPI would be great !

Best

Oliver

**Comment by Spacechild1** [comment]
> If possible, use the issue tracker at https://git.iem.at/pd/vstplugin/-/issues. 

;-)
